# Generated by Django 5.1.4 on 2025-01-08 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="user_id",
            new_name="user",
        ),
    ]
