# Generated by Django 5.1.4 on 2025-01-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_user_id_usersession_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="session_start",
            new_name="login_time",
        ),
        migrations.RenameField(
            model_name="usersession",
            old_name="session_end",
            new_name="logout_time",
        ),
        migrations.AlterField(
            model_name="activityuser",
            name="button_name",
            field=models.CharField(max_length=50),
        ),
    ]
