# Generated by Django 5.1.4 on 2025-01-09 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_session_start_usersession_login_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="login_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
