# Generated by Django 5.1.4 on 2025-01-09 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_usersession_login_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
